services:
  - type: web
    name: radiology-api
    env: python
    plan: free
    # IMPORTANT: Make sure this is the correct URL to your main repository
    repo: https://github.com/your-username/hnzpriority.git
    branch: main
    # --- The key fix is here ---
    # Tell Render to look inside this subdirectory for the backend code.
    rootDir: ./radiology-cleaner-app/backend
    buildFilter:
      paths:
        # Only trigger a new build if files in the backend folder change.
        - "radiology-cleaner-app/backend/**"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_VERSION
        value: 23.2.1
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
