# This file defines both our staging and production backend services.
# Render will create and manage both based on this configuration.
services:
  # --- Staging Service ---
  # Deploys automatically from the 'develop' branch
  - type: web
    name: radiology-api-staging
    env: python
    plan: free # Can be changed to a paid plan if needed
    repo: https://github.com/twocolddogs/HNZpriority.git
    branch: develop # Watches the develop branch
    rootDir: ./radiology-cleaner-app/backend
    buildFilter:
      paths:
        - "radiology-cleaner-app/backend/**"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_VERSION
        value: 23.2.1
      - key: PORT
        value: 10000  # Explicitly set the PORT
    buildCommand: "./build.sh"
    # --- FIXED START COMMAND ---
    startCommand: "gunicorn --workers 1 --bind 0.0.0.0:10000 --timeout 120 app:app"
    autoDeploy: true # Automatically deploy on push to 'develop'
    healthCheckPath: /  # Add a health check path if your app has one
    
  # --- Production Service ---
  # Deploys manually from the 'main' branch
  - type: web
    name: radiology-api-prod
    env: python
    plan: free # Can be changed to a paid plan for production
    repo: https://github.com/twocolddogs/HNZpriority.git
    branch: main # Watches the main branch
    rootDir: ./radiology-cleaner-app/backend
    buildFilter:
      paths:
        - "radiology-cleaner-app/backend/**"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_VERSION
        value: 23.2.1
      - key: PORT
        value: 10000  # Explicitly set the PORT
    buildCommand: "./build.sh"
    # --- FIXED START COMMAND ---
    startCommand: "gunicorn --workers 1 --bind 0.0.0.0:10000 --timeout 120 app:app"
    autoDeploy: false # CRITICAL: Prevents accidental deployments to production
    healthCheckPath: /  # Add a health check path if your app has one
