# This file defines both our staging and production backend services.
# Render will create and manage both based on this configuration.

services:
  # --- Staging Service ---
  # Deploys automatically from the 'develop' branch
  - type: web
    name: radiology-api-staging
    env: python
    plan: free # Can be changed to a paid plan if needed
    repo: https://github.com/twocolddogs/hnzpriority.git # IMPORTANT: Change this!
    branch: develop # Watches the develop branch
    rootDir: ./radiology-cleaner-app/backend
    buildFilter:
      paths:
        - "radiology-cleaner-app/backend/**"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_VERSION
        value: 23.2.1
    buildCommand: "./build.sh"
    # --- FIXED START COMMAND ---
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    autoDeploy: true # Automatically deploy on push to 'develop'

  # --- Production Service ---
  # Deploys manually from the 'main' branch
  - type: web
    name: radiology-api-prod
    env: python
    plan: free # Can be changed to a paid plan for production
    repo: https://github.com/twocolddogs/hnzpriority.git # IMPORTANT: Change this!
    branch: main # Watches the main branch
    rootDir: ./radiology-cleaner-app/backend
    buildFilter:
      paths:
        - "radiology-cleaner-app/backend/**"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_VERSION
        value: 23.2.1
    buildCommand: "./build.sh"
    # --- FIXED START COMMAND ---
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    autoDeploy: false # CRITICAL: Prevents accidental deployments to production
