services:
- type: web
  name: radiology-api-staging
  env: python
  plan: free
  repo: https://github.com/twocolddogs/HNZpriority.git
  branch: develop
  rootDir: ./radiology-cleaner-app/backend
  buildFilter:
    paths:
      - "radiology-cleaner-app/backend/**"
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.6
    - key: PIP_VERSION
      value: 23.2.1
    - key: PIP_CACHE_DIR
      value: /opt/render/.cache/pip
  buildCommand: "chmod +x build.sh && ./build.sh"
 
  startCommand: "chmod +x start.sh && ./start.sh"
  autoDeploy: false
  healthCheckPath: /health

- type: web
  name: radiology-api-prod
  env: python
  plan: free
  repo: https://github.com/twocolddogs/HNZpriority.git
  branch: main
  rootDir: ./radiology-cleaner-app/backend
  buildFilter:
    paths:
      - "radiology-cleaner-app/backend/**"
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.6
    - key: PIP_VERSION
      value: 23.2.1
    - key: PIP_CACHE_DIR
      value: /opt/render/.cache/pip
  buildCommand: "chmod +x build.sh && ./build.sh"
 
  startCommand: "chmod +x start.sh && ./start.sh"
  autoDeploy: false
  healthCheckPath: /health

- type: static
  name: radiology-cleaner-frontend-staging
  repo: https://github.com/twocolddogs/HNZpriority.git
  branch: develop
  rootDir: ./radiology-cleaner-app/
  buildFilter:
    paths:
      - "radiology-cleaner-app/frontend/**"
  buildCommand: echo "Static files - no build needed"
  staticPublishPath: ./
  pullRequestPreviewsEnabled: true
  routes:
    - type: rewrite
      source: /api/(.*)
      destination: https://radiology-api-staging.onrender.com/$1
    - type: rewrite
      source: /*
      destination: /index.html

- type: static
  name: radiology-cleaner-frontend-prod
  repo: https://github.com/twocolddogs/HNZpriority.git
  branch: main
  rootDir: ./radiology-cleaner-app/
  buildFilter:
    paths:
      - "radiology-cleaner-app/**"
  buildCommand: echo "Static files - no build needed"
  staticPublishPath: ./
  routes:
    - type: rewrite
      source: /api/(.*)
      destination: https://radiology-api-prod.onrender.com/$1
    - type: rewrite
      source: /*
      destination: /index.html