services:

# - Staging Service -

- type: web
  name: radiology-api-staging
  env: python
  # NOTE: The free plan has very limited memory (512MB). If you continue to see
  # memory-related errors, you will need to upgrade to the "Starter" plan.
  plan: free
  repo: https://github.com/twocolddogs/HNZpriority.git
  branch: develop
  rootDir: ./radiology-cleaner-app/backend
  buildFilter:
    paths:
      - "radiology-cleaner-app/backend/**"
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.6
    - key: PIP_VERSION
      value: 23.2.1
    # Memory optimization for SpaCy
    - key: SPACY_MAX_LENGTH
      value: 1000000
  buildCommand: "chmod +x build.sh && ./build.sh"
  # CORRECTED: Increased timeout to 300s to allow for heavy model loading on first request.
  startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 300 --preload --log-level debug app:app"
  autoDeploy: true
  # CORRECTED: Pointed health check to the correct /health endpoint in your app.py
  healthCheckPath: /health

# - Production Service -

- type: web
  name: radiology-api-prod
  env: python
  # NOTE: The free plan has very limited memory (512MB). If you continue to see
  # memory-related errors, you will need to upgrade to the "Starter" plan.
  plan: free
  repo: https://github.com/twocolddogs/HNZpriority.git
  branch: main
  rootDir: ./radiology-cleaner-app/backend
  buildFilter:
    paths:
      - "radiology-cleaner-app/backend/**"
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.6
    - key: PIP_VERSION
      value: 23.2.1
    - key: SPACY_MAX_LENGTH
      value: 1000000
  buildCommand: "chmod +x build.sh && ./build.sh"
  # CORRECTED: Increased timeout to 300s to allow for heavy model loading on first request.
  startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 300 --preload --log-level info app:app"
  autoDeploy: false
  # CORRECTED: Pointed health check to the correct /health endpoint in your app.py
  healthCheckPath: /health